# Run shellcheck and shfmt
name: Lint checks
on: [push, pull_request]
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: shellcheck
      uses: bewuethr/shellcheck-action@v2
  shfmt-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.14.2'
    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Run shfmt
      run: |
        GO111MODULE=on go get mvdan.cc/sh/v3/cmd/shfmt
        while read -r f; do
          PATH=$HOME/go/bin:$PATH shfmt -ci -d -i 4 $f
        done < <(find . -type f -name "*.sh")
